// @ai-context
// CRDT 变更集 handlers：Automerge 二进制变更（base64）的追加式推送与增量拉取。
// CRDT changeset handlers: append-only push and incremental pull of base64 Automerge changes.
// Why: 服务端不解析 changeset 内容，只做不可变存储与序号分配，合并语义完全由客户端 Automerge 负责。
package handlers

import (
	"net/http"
	"strconv"

	"entropydecrease/sync-service/models"

	"github.com/gin-gonic/gin"
	"gorm.io/gorm"
)

// ─── CRDT Changeset Push (POST /api/v1/sync/crdt/changes) ─────────────────────

type crdtPushRequest struct {
	DeviceID string `json:"deviceId"`
	Changes  []struct {
		Seq       int64  `json:"seq"` // client-side seq (for acknowledgement)
		TableName string `json:"tableName"`
		EntityID  string `json:"entityId"`
		Changeset string `json:"changeset"` // base64 Automerge changes
		Operation string `json:"operation"` // create|update|delete
		CreatedAt string `json:"createdAt"`
	} `json:"changes"`
}

// CRDTPush accepts a batch of CRDT changesets from a client and stores them.
// Each changeset is assigned a server-side sequence number (GlobalSeqNo).
func CRDTPush(c *gin.Context) {
	var req crdtPushRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	userID := c.GetString("user_id")
	accepted := make([]int64, 0) // client-side seq numbers that were accepted
	pushErrors := make([]string, 0)

	for _, ch := range req.Changes {
		var serverSeq int64

		txErr := models.DB.Transaction(func(tx *gorm.DB) error {
			seqNo, err := nextSeqNo(tx)
			if err != nil {
				return err
			}
			serverSeq = seqNo

			return tx.Create(&models.CRDTChange{
				ServerSeqNo: seqNo,
				DeviceID:    req.DeviceID,
				UserID:      userID,
				TableName:   ch.TableName,
				EntityID:    ch.EntityID,
				Changeset:   ch.Changeset,
				Operation:   ch.Operation,
				CreatedAt:   ch.CreatedAt,
			}).Error
		})

		if txErr != nil {
			pushErrors = append(pushErrors, "crdt tx error: "+txErr.Error())
			continue
		}
		_ = serverSeq // serverSeq is assigned but client uses its own seq for ack
		accepted = append(accepted, ch.Seq)
	}

	c.JSON(http.StatusOK, gin.H{
		"accepted": accepted,
		"errors":   pushErrors,
	})
}

// ─── CRDT Changeset Pull (GET /api/v1/sync/crdt/changes) ──────────────────────

// CRDTPull returns all CRDT changesets since `since` (exclusive) that were
// NOT generated by the requesting device.
// Query params: since (int64), deviceId (string)
func CRDTPull(c *gin.Context) {
	userID := c.GetString("user_id")
	deviceID := c.Query("deviceId")
	sinceStr := c.DefaultQuery("since", "0")
	since, err := strconv.ParseInt(sinceStr, 10, 64)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid since parameter"})
		return
	}

	var changes []models.CRDTChange
	if err := models.DB.
		Where("user_id = ? AND server_seq_no > ? AND device_id != ?", userID, since, deviceID).
		Order("server_seq_no ASC").
		Find(&changes).Error; err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	result := make([]gin.H, 0, len(changes))
	var latestSeq int64 = since

	for _, ch := range changes {
		result = append(result, gin.H{
			"seq":       ch.ServerSeqNo,
			"tableName": ch.TableName,
			"entityId":  ch.EntityID,
			"changeset": ch.Changeset,
			"operation": ch.Operation,
			"deviceId":  ch.DeviceID,
			"createdAt": ch.CreatedAt,
		})
		if ch.ServerSeqNo > latestSeq {
			latestSeq = ch.ServerSeqNo
		}
	}

	c.JSON(http.StatusOK, gin.H{
		"changes":   result,
		"latestSeq": latestSeq,
	})
}
